### ISSUE TITLE
Styling & Animation journal (II)

### ISSUE THREAD

**Issue by kwartalex** [kwartalex/capstone-project#10]
##VALUE STATEMENT

As a gratitude journal keeper
I enjoy a clearly laid out and intuitive interface
so that even if I use my app every day I can still find my way around my entries comfortably .

---

##DESCRIPTION

All entries are clearly separated from one another and only the first bit shows when scrolled through them. Only when clicked does the entire entry show which can also be closed again.

---

##ACCEPTANCE CRITERIA

- [ ] entries can be opened & closed
- [ ] visual effect on open entries: new color background
---
##TASKS

- [ ]  implement open icon 
- [ ]  implement open functionality
- [ ]  implement close icon 
- [ ]  implement close functionality
- [ ]  scroll if text is longer
- [ ]  implement open color change

---

##SIZE
Medium
