### ISSUE TITLE
Local Storage & touchpoint visualisation (I)

### ISSUE THREAD

**Issue by kwartalex** [kwartalex/capstone-project#2]
## VALUE STATEMENT
As a user of the gratitude journal app
I would love to browse through all my previous entries
so that I can relive everyday and remember all the things I can be thankful for.

---

## DESCRIPTION
After a diary entry was added, it is being saved and chronologically to the app. Adding more entries will make them pile up chronologically on top of each other. 

---

## ACCEPTANCE CRITERIA
- [ ] generated text sections are saved to local storage
- [ ] a submit clears the input field
- [ ] before and after the submit the input field has focus

---

## TASKS
- [ ] implement local storage
- [ ] implement focus
- [ ] implement clear functionality
- [ ] implement visual signal to confirm button submit

## SIZE
Medium

![20200429_Scribble_Story1](https://user-images.githubusercontent.com/61711399/80613040-07fed200-8a3d-11ea-90f4-d132b03cb285.JPG)
