### ISSUE TITLE
Hosting app & testing of functions (II)

### ISSUE THREAD

**Issue by kwartalex** [kwartalex/capstone-project#6]
## VALUE STATEMENT
As a developer of the gratitude journal app
I need to be sure of a stable environment
so that I can supply the app users with a fully and smoothly functioning app.

---

## DESCRIPTION
The app is hosted and all functionalities are backed up with component tests. 

---

## ACCEPTANCE CRITERIA
- [ ] Hosting is running
- [ ] Tests are implemented

---

## TASKS
- [ ] implement max. input
- [ ] implement firebase hosting
- [ ] implement tests for input
- [ ] implement tests for diary entries (delete)
- [ ] implement stories for Button
- [ ] implement stories for Navigation

## SIZE
Medium
